### ISSUE TITLE
Efficiency Testing

### ISSUE THREAD

**Issue by mailemccann** [AguaClara/ram_pump#16]
Efficiency: (Q_pumped * H_pumped)/(Q_wasted * H_drivepipe)

Previous configuration from Spring 2017:

Inverted Configuration:

**Comment by mailemccann** [comment]
We are having trouble measuring pressure to calculate head in the effluent pipe due to the inaccuracy of the pressure sensors

**Comment by stevenlopez182** [comment]
An idea for that is to reduce the length of the tubing that connects the ram pump to the pressure sensor, and also to allow water to flow through the tubing before attaching it so there isn't any entrapped air
