### ISSUE TITLE
CAD Drawing: Inverted Configuration

### ISSUE THREAD

**Issue by mailemccann** [AguaClara/ram_pump#19]
[Schematic of inverted configuration.pdf](https://github.com/AguaClara/ram_pump/files/1802697/Schematic.of.inverted.configuration.pdf)
 This is a CAD drawing of the inverted configuration that we are currently testing.

**Comment by nataliemottl** [comment]
Do you also have a Fusion 360 version or is there a specific reason why you chose to work in AutoCAD?
