### ISSUE TITLE
Ordering Parts

### ISSUE THREAD

**Issue by mailemccann** [AguaClara/ram_pump#2]
Parts to order (ask Anna)
-Plastic Union
-Possibly relief valve
-Longer plate

**Comment by nataliemottl** [comment]
How are you guys doing with this? Have you ordered everything necessary?

**Comment by WillLopez** [comment]
We were able to obtain a makeshift plastic union (purchased at Lowes) and instead of using a longer plate, we increased the plate amplitude by adjusting the top standoff position on the threaded rod.  The ram pump is now functional, so we didn't need to order these new parts yet.
