### ISSUE TITLE
Force analysis for k minimum

### ISSUE THREAD

**Issue by mailemccann** [AguaClara/ram_pump#22]
Parameters
F hydrostatic < f(x) < F drag
Can decrease drag, cannot change hydrostatic
To minimize k, need to minimize drag force
Looking for minimum k that will create a spring force greater than hydrostatic force when in the f(x_max) position

**Comment by stevenlopez182** [comment]
When solving for the ideal spring constant also need to account for the variability in the length and area of the spring and include them as parameters to be solved for

**Comment by WillLopez** [comment]
Spring force while the plate is closed should be slightly larger than the hydrostatic force of the water column above.  While the plate is opening, the spring force decreases.
