### ISSUE TITLE
3/20 Force Calculations

### ISSUE THREAD

**Issue by mailemccann** [AguaClara/ram_pump#23]
- Using python code, calculated hydrostatic force when plate closed to be 2.5 N

- Max drag force when plate is completely open is 10.56 N as per last semester's Python Code

- Need to ensure that plate can open completely- must overcome hydrodynamic force while plate is partially open

Calculations below:

![1334x1334 jpeg b8060b7d54884c8f9478d970df6350a2](https://user-images.githubusercontent.com/33263256/37685911-a7d16608-2c6b-11e8-8026-64327e3e21cd.jpg)
![1334x1334 jpeg fbbd7bca11dc44bc9db939827c5d8951](https://user-images.githubusercontent.com/33263256/37685915-a9e5164c-2c6b-11e8-83d8-61416fd529f7.jpg)

**Comment by stevenlopez182** [comment]
I agree with this

**Comment by mailemccann** [comment]
Thanks for the support @stevenlopez182

**Comment by mailemccann** [comment]
Goals for next meeting:

- Measure max displacement (current amplitude)

- Decide k value that can resist 2.5 N but is closed when 10.56 N applied

- Order new springs in range

**Comment by mailemccann** [comment]
3/21 - All goals completed
