### ISSUE TITLE
Finding the pressure of the effluent for efficiency calculation

### ISSUE THREAD

**Issue by stevenlopez182** [AguaClara/ram_pump#26]
We are attempting to connect pressure sensors to procoda to get the effluent pressure but the readings for all the 200 kPa sensors we've tried are unstable and we have been unable to find a functional 7 kPa sensor

**Comment by WillLopez** [comment]
We will calculate the ram pump efficiency using the effluent pressure values that we measured from the 200 kPa sensor.
