### ISSUE TITLE
Efficiency Testing 4/10

### ISSUE THREAD

**Issue by stevenlopez182** [AguaClara/ram_pump#27]

**Comment by stevenlopez182** [comment]
Effluent Volume - 400 mL = .4 L
Waste Volume - 2.45 L
Time - 12 s 
Efficiency = (Q_pumped * H_pumped)/(Q_wasted * H_drivepipe)
E = (.4 * 10 )/(2.45 *1.91 )

Spring # 10479

CSC Stock # 10479 
OD (in) 0.312  
ID (in) 0.272  
Free Length (in) 3.660  
Rate (lbs/in) 0.360  

![spring](https://user-images.githubusercontent.com/33263256/38640023-83ccec2e-3dc2-11e8-9dc4-788464a23359.jpg)

**Comment by mailemccann** [comment]
https://docs.google.com/presentation/d/1FNUxLjklz7i8IUZNYqKr_FwFPTlFwUQ9zAzDU84ph2I/edit#slide=id.g1a494589a6_4_71

**Comment by mailemccann** [comment]
This is the efficiency testing of a newly ordered spring with specifications shown above
