### ISSUE TITLE
Efficiency Testing 4/11

### ISSUE THREAD

**Issue by mailemccann** [AguaClara/ram_pump#28]
Test 1
k value = .46
length = .062 m

Waste volume: 2.6 - .75 = 1.85 gal = 7 L
Effluent Volume: .76 L
E = (10*.76)/(1.91*7)
E = 55%

Test 2
Specs from new spring, from 4/10
Waste Volume: 1.65 gal = 6.25 L
Effluent Volume: .82 L 
E = (10*.82)/(1.91*6.25)
E = 68.9%

**Comment by mailemccann** [comment]
Fall 2016 Research Report, where we extracted values for effluent head

https://confluence.cornell.edu/display/AGUACLARA/Ram+Pump?preview=/152026512/340901334/RamPumpFinalReportFall2016.pdf

**Comment by monroews** [comment]
This efficiency are incredibly high. Was there a consistent 10 m of head on the pumped water side?

**Comment by mailemccann** [comment]
No, the 10 m head is an averaged value and it was actually extracted from the Fall 2016 research report in their efficiency testing. We had very inaccurate readings for effluent pressure due to excessive noise in the pressure sensor reading and low sensitivity on the 200 and 7kpa pressure sensors. 

The efficiency values were alarming to us and we are meeting today to go through more iterations of the efficiency test and try and obtain a more accurate pressure reading for the effluent
