### ISSUE TITLE
4/13 Efficiency Testing

### ISSUE THREAD

**Issue by mailemccann** [AguaClara/ram_pump#30]
Testing Efficiency through air chamber instead of from effluent

Volume of water in cylinder: h*pi*r^2 = (.415)*pi*(.024)^2 = .00075 m^3 = .75 L
Volume of Waste: 2.25 gal = 8.52 L
Effluent Head: 13.65 m
E = (.75*13.65)/(1.91*8.52)
E = 62.91%

**Comment by stevenlopez182** [comment]
Looks good I like what your team is doing
