### ISSUE TITLE
Update on Python Code

### ISSUE THREAD

**Issue by mailemccann** [AguaClara/ram_pump#35]
The past week we have been working on a Python code to find the idealized maximum efficiency for the pump under a set of experimental conditions. This allows us to see how far off we are from that maximum efficiency and what the biggest contributors to loss of efficiency are.

The goal of the rest of the semester is to set up our code and calculations so that next semester's team can work more efficiently and have a faster learning curve. 

https://github.com/AguaClara/ram_pump/blob/master/IdealEfficiency.py

**Comment by mailemccann** [comment]
We are also working on analyzing experimental pressure data via ProCoDa_parsing python code in AguaClara_research repository in order to determine our efficiency.

**Comment by stevenlopez182** [comment]
<img width="315" alt="ideal velocity graph" src="https://user-images.githubusercontent.com/33263256/39650655-029ba99a-4fb7-11e8-8946-516825f180e5.png">

**Comment by WillLopez** [comment]
Additionally, we measured effluent head using ProCoDa and will be including the data analysis in our code
