### ISSUE TITLE
Testing Inverted Configuration

### ISSUE THREAD

**Issue by mailemccann** [AguaClara/ram_pump#4]
Plate entered under valve instead of over, default position is down

**Comment by mailemccann** [comment]
Need to drill effluent valve in top check valve via CEE lab

**Comment by monroews** [comment]
The CEE shop can do this. Note that this is called tapping and you'll want to take them the high pressure check valve so they can tap the hole correctly.

**Comment by mailemccann** [comment]
Thank you- the valve to be tapped is in the CEE lab now along with the high pressure check valve for reference, should be done by Monday afternoon.

**Comment by WillLopez** [comment]
Machine shop closed upon arrival today, testing of the inverted configuration will occur promptly at 14:30 tomorrow 2/28.
