### ISSUE TITLE
new idea for finding k value

### ISSUE THREAD

**Issue by AlyciaStorch** [AguaClara/ram_pump#41]
find k by doing (delta F)/x where delta F is the difference between hydrostatic force and force from water moving at .5Vf and x is 1.3 cm. That gives us k and then we just need to plug that into F=kx for hydrostatic force and moving water force to find the needed original and final compressions of the spring. This should be our ideal k value and then we can work from there to find a good range based on things like water enver getting to v=0 and headloss and whatnot.

**Comment by mailemccann** [comment]
How did this go?
