### ISSUE TITLE
Spring 2019 Goals

### ISSUE THREAD

**Issue by ChingPangggg** [AguaClara/ram_pump#57]
Weekly:
Week of 3/4/2019:

- [x] Order parts to fabricate a new ram pump
- [x] Edit Research Report
- [x] CAD drawings of spring and check valve
- [x] Empirical calculation of forces

End-of-Semester Goals:

**Comment by cheertsang** [comment]
### **Weekly Goals:**

_Week of 3/4/2019_
- [x] Edit Research Report
- [ ] Understand efficiency graph
- [x] Run tests by pulling on valve manually, analyze pressure graphs
- [ ] Air chamber, ideal gas law

Standard pipe sizes for each plant?

**Comment by alyssaju** [comment]
### **Weekly Goals:**

_Week of 3/4/2019_
- [x] Learn/research more about fluid dynamics and physics of Ram Pump
- [x] Understand code of mathematical model (efficiency graph)
- [x] Process collected manual pressure data points

_Week of 3/11/2019_
- [x] Work on Research Draft II
- [x] Work on symposium

_Week of 3/18/2019_
- [ ] Edit research paper draft 2
- [ ] Outline first section of EPA grant phase 2

_Week of 3/25/2019_
- [ ] Recalculate terminal velocity of water in drive pipe

**Comment by inigocabrera44** [comment]
Week of 3/4/2019

- [ ] Learn/Understand the pressures regenerated at the Pump (including air chamber).
- [ ] Run the test and learn how to set up the rum pump with ProCoda and how to transfer and collect the data to Atom at our laptops.
- [ ] Empirical calculation of forces
