### ISSUE TITLE
Pressure cycles observed with setting initial pressure

### ISSUE THREAD

**Issue by ChingPangggg** [AguaClara/ram_pump#58]
We set the set the air chamber's initial pressure to be 600 kPa, and we ran the system by manually control the opening and closing of the valve. We obtained the graphs as shown below:
![image](https://github.com/AguaClara/ram_pump/blob/master/pressure_trace_initialpressure1.jpg?raw=True)
![image](https://github.com/AguaClara/ram_pump/blob/master/pressure_trace_initialpressure2.jpg?raw=True)
@monroews these are the two graphs that we generated

**Comment by ChingPangggg** [comment]
@monroews Could you please advise us on what should we interpret from it? I am also a bit confused  about what we should be looking at from the wasteline pressure graph. Thank you very much.

**Comment by monroews** [comment]
10 m of elevation would be 100 kPa. So I'm wondering how you selected 600 kPa. Note that the pressure sensor that you are using is rating for 200 kPa.
How did you achieve such a high pressure? I'm actually very suspicious that you have incorrect calibrations for the pressure sensors. Is the drive pipe pressure sensor installed backwards? 
The drive pipe pressure never reaches the pressure of the air chamber and yet clearly water is being pumped from the drive pipe into the air chamber. 

Is it possible that the units on these graphs are centimeters?

The change in pressure in the air chamber with each pump cycle can be used to calculate how much water was pumped in each cycle. Use PV=nRT. You need to know the initial volume of air and then you can predict the volume of air as a function of pressure. Then you can take the change in air pressure at each pump cycle to measure the amount of water that was pumped.

You can also study one pump cycle. Show the drive pipe pressure above the waste valve for about 1 second after the valve closure. THen you should be able to identify the pump part of the cycle. The pump part of the cycle is where the pressure is decreasing rapidly right after the valve slams shut. You can use F=ma to see if the duration of the deceleration makes sense. You can also estimate the volume pumped based during one cycle based on your knowledge of the initial velocity in the drive pipe.

You've got lots of cool analysis you can do after you fix the pressure sensor calibrations.

**Comment by cheertsang** [comment]
@ChingPangggg the pressure was 600 cm, since I added both pressure sensors with units in cm of water (Both are 200 kPa sensors).

**Comment by ChingPangggg** [comment]
@monroews We actually pressurized the air chamber to be 600 cm, and then start running the experiment. Would you mind clarifying how pressurizing it initially can help us observe the cycle? Are we pressurizing it because we want to to allow the water to travel up to 6m (600cm), and we want to observe the pressure change if the air chamber starts at 600 cm of pressure?

We are calculating the water being pumped using ideal gas law with delta P being the change of pressure in the air chamber at each cycle, and then using delta V=nRT/delta P, we can find delta V as the change of volume of the air in the chamber, and then how can we relate the initial volume of air in the chamber to find the volume of the water bring pumped into the chamber in each cycle? For our experimental setup, how should the change in volume of air and change in volume of water?

**Comment by monroews** [comment]
reason to pressurize to 6 m is to mimic what the ram pump will be doing in a real plant.
You want to know how much water the ram pump can pump when lifting water 6 or more meters.

change in air volume = - change in water volume
Set up this analysis in python. Show me what you find!

Also don't forget to look at the pump part of the cycle in more detail to see the time when the water is decelerating in the drive pipe.

**Comment by mailemccann** [comment]
@ChingPangggg I don't think you need to relate to the initial volume in the chamber; you're just looking for the delta V for one pump cycle, eg: how much water was pumped in that individual cycle

**Comment by monroews** [comment]
You will need to know how many moles of air are in the chamber. You get that by knowing the pressure and volume at some point. Can be initial or final or random. Happily mass is conserved.

**Comment by cheertsang** [comment]
![graph](https://raw.githubusercontent.com/AguaClara/ram_pump/master/one_cycle.jpg)

We took one cycle and found the pressure change in the air chamber using this code:

```
import aguaclara.research.procoda_parser as pp
import matplotlib.pyplot as plt
import numpy as np
import aguaclara.core.physchem as pc
import aguaclara.core.constants as c

#find volume of air using ideal gas law
#deltaV = nRT/deltaP

#pressure difference, deltaP (measured as difference in pressure in air chamber)
url = 'https://raw.githubusercontent.com/AguaClara/ram_pump/master/Spring%202019/3-7-19_manual_operationwith650Pitrial2.xls'

start = 7000 #should be more than 'start'
end = 10000 #should be less than 'stop'

airchamber = pp.column_of_data(url, start, 2, end, 'cm')

head = airchamber[-1]-airchamber[0]

#n, initial number of moles of air
diam = 1*u.inch
height_water = 1.5 * u.inch #initial height of water in air chamber
vol_water = (pc.area_circle(diam)*height_water).to(u.m**3) #initial volume of water in air chamber
height_ac = 26.5*u.inch #height of air chamber
vol_airchamber = (pc.area_circle(diam)*height_ac).to(u.m**3)

init_vol = vol_airchamber - vol_water #initial volume of air in air chamber
mass = (c.AIR_DENSITY*init_vol).to(u.kg)
mol_mass = 28.97*u.g/u.mol

n = (mass/mol_mass).to(u.mol)

#gas constant
R = 8.314 * u.J/(u.mol*u.K)

#standard temp
T = 293*u.K

#convert head to pressure
deltaP = (pc.density_water(T)*c.GRAVITY*head).to(u.Pa)

#calculate change in volume of air, which is equal to the volume of water pumped
deltaV = ((n*R*T)/(deltaP)).to(u.m**3)
print('The volume of water pumped per cycle is ' + str(deltaV))
```

**The volume of water pumped per cycle is 2.033e+07 meter ** 3 ...which seems extremely unreasonable?**

**Comment by cheertsang** [comment]
@monroews We figured out that the [constants.py](https://github.com/AguaClara/aguaclara/blob/master/aguaclara/core/constants.py) package provides the density of air as 1.204 kilogram/millimeter^3 (AIR_DENSITY), when this should be 1.204 kilogram/meter^3.

**The volume of water pumped per cycle is 0.02033 meter ** 3**

**Comment by monroews** [comment]
Convert to units that are easy to understand. mL?
Post an issue on aguaclara repo re the error in air density. Propose that air density should NOT be a constant! It should be calculated from PV=nRT.

Add units to your x axis!

Create a graph that shows just the pump cycle. The pump cycle likely lasts a fraction of a second and corresponds with the increase in pressure in the air chamber. See if you have enough data to describe that event well. You might need a higher data rate. I'm a little confused about the pressure trace for the drive pipe. Is it possible that you are plotting the negative of the pressure?

**Comment by cheertsang** [comment]
@monroews  I updated the graphs above so that the pressure is positive for both sensors and added units to the x axis. This makes sense to me for the air chamber pressure, because when the valve closes, the pressure in the chamber increases as water is pumped in.

However, I am confused as to why the pressure in the waste valve has a positive spike when the valve is closed. **What insight can we gain from the waste valve pressure traces?**

**Comment by monroews** [comment]
The pressure traces suggest that the pressure above the waste valve was never high enough to pump any water into the air chamber. I'd check how the sensors were zeroed and suggest checking to see if they read the same value when measuring the same pressure.

I'd propose that mL is easier to understand than cubic meters for the flows you are generating.

Once you have that corrected pressure trace then it should be possible to see the length of the time that the waste valve pressure exceeded the air chamber pressure. You should be able to compare that duration with the length of the pump cycle that you predicted based on F=ma. You can also compare the volume pumped with the predicted volume of water pumped based on F=ma and Q=VA.

**Comment by cheertsang** [comment]
We zeroed the pressure sensors at atmospheric pressure. We also checked to see if they read about the same value when measuring the same pressure, and they do. We also made sure the pressure sensors were attached the right way so that we didn't get negative pressure readings. 
![Capture](https://user-images.githubusercontent.com/35718077/54774770-db924880-4be2-11e9-9755-1b77d8798197.PNG)

**From my understanding, the waste valve pressure should reach the air chamber pressure in order to pump water into the air chamber? Is it not reaching the air chamber pressure because we pressurized the air chamber at 600 cm and there isn't enough head to pump water into the air chamber?**

**Comment by monroews** [comment]
So now run some pump cycles again and track the air chamber pressure to see if you are pumping water.

**Comment by cheertsang** [comment]
Water is definitely being pumped into the air chamber, so the waste valve pressure should reach the air chamber pressure, but it is not doing that

**Comment by monroews** [comment]
Are you getting pressure traces that show when the valve cycles?

**Comment by cheertsang** [comment]
Are the graphs we generated above the pressure traces when the valve cycles?
And the one below is showing the pressure of one cycle?
We also checked that the pressure sensors were attached the right way. Pushing on the side that is exposed to the atmospheric pressure(not the ram pump) causes the pressure to decrease. But we are confused about why we are getting a negative waste valve pressure. Ans we zeroed it at atmospheric pressure.
![pressurecycle3](https://github.com/AguaClara/ram_pump/blob/master/Spring%202019/Images_Diagrams/pressure_trace_initialpressure3.jpg?raw=true)

**Comment by monroews** [comment]
That graph looks like old data from before you zeroed the pressure sensors.

**Comment by cheertsang** [comment]
We zeroed the pressure sensors before water started running through the system. This graph below shows the pressure when water is running through the system. Should we zero it at this point?
![image](https://user-images.githubusercontent.com/35718077/54869951-3ad49200-4d76-11e9-81c9-a61e03712108.png)

**Comment by cheertsang** [comment]
We zeroed it when the water started running through the system, but the waste valve pressure still never reaches the air chamber pressure, even though we can see that water is being pumped into the air chamber.
![pressure0323](https://github.com/AguaClara/ram_pump/blob/master/Spring%202019/Images_Diagrams/pressure_trace_initialpressure0323_0.jpg?raw=true)

**Comment by monroews** [comment]
You know that this pressure data can't be right.
Hypotheses???

- one or more of the pressure sensors isn't calibrated correctly. This would mean that if both pressure sensors were connected to the air chamber they would report different pressures.
- The high speed pressure pulse doesn't reach the waste valve pressure sensor because it is attenuated by the flow of water and compression of air in that sample line. If this is happening (you can watch the water moving in this tube while the ram pump is cycling!) then you could eliminate this problem by filling this tube the whole way (minus the last 5 cm or so).

**Comment by ChingPangggg** [comment]
We've checked the calibration of the pressure sensors by connecting them to the air chamber and they read the same pressure, so we are fairly certain that this is not the issue. 

**Should we zero the pressure sensors before we start running water through the system? Or once we've started running the system and filled up the air chamber almost all the way?**

We have observed the water in the air chamber increase every time the valve closes, so we know for sure that water is being pumped into the air chamber. We will try running the system by filling up the air chamber almost all the way, and see what we get.

**Comment by monroews** [comment]
The pressure sensors should be zeroed when they are both at atmospheric pressure.
Please check my second hypothesis. The high speed pressure pulse doesn't reach the waste valve pressure sensor because it is attenuated by the flow of water and compression of air in that sample line. If this is happening (you can watch the water moving in this tube while the ram pump is cycling!) then you could eliminate this problem by filling this tube the whole way (minus the last 5 cm or so).

**Comment by ChingPangggg** [comment]
We zeroed both sensors a atmospheric pressure, and then filled the air chamber all the way, leaving the last 8 cm. However, the waste valve pressure is still much lower than the air chamber pressure. We also obtained the total volume of water pumped for the duration of our data to be 0.0718 L.

![pressurefilledchamber](https://github.com/AguaClara/ram_pump/blob/master/Spring%202019/Images_Diagrams/pressure_trace_initialpressure0323_1.jpg?raw=true)

**Comment by ChingPangggg** [comment]
We also did another trial, and we obtained the total volume of water pumped for the duration of our data (10 cycles) to be 0.099 L, which is around 10mL per cycle.
![10cycles](https://raw.githubusercontent.com/AguaClara/ram_pump/master/Spring%202019/Images_Diagrams/pressure_trace_initialpressure0323_3.jpg)

**Comment by monroews** [comment]
Please check my 2nd hypothesis

**Comment by ChingPangggg** [comment]
We shortened the tubing connecting the pressure sensor at the waste valve position. We ran a test again and obtained the following graphs:

We manually opened and closed the plate for 16 times (timing is selected arbitrarily), and we found that approximately 0.2149 L was pumped in total, which means that approximately 0.0134 L was pumped per each cycle.
![graph0325_0](https://github.com/AguaClara/ram_pump/blob/master/Spring%202019/Images_Diagrams/pressure_trace_initialpressure0325_new.jpg?raw=true)

We ran another trial, and the total volume pumped is 0.5182L, and the volume pumped per each cycle is 0.0324 L.
![graph0325_1](https://github.com/AguaClara/ram_pump/blob/master/Spring%202019/Images_Diagrams/pressure_trace_initialpressure0325_new1.jpg?raw=true)

**Comment by monroews** [comment]
Excellent!
Can you show full detail of one pump cycle? You may need to increase the data rate (both acquisition rate and rate of saving to file).

How much air do you have in the pressure sensor line?
