### ISSUE TITLE
RA Comments on Symposium

### ISSUE THREAD

**Issue by mailemccann** [AguaClara/ram_pump#63]
Hey all, great job on symposiums last week! Here are my comments and suggestions for improvement before the final presentation:
- Emphasize how the vertical ram pump improves fabrication capabilities- ability to insert into already existing pipe (I think a lot of people miss this aspect)
- Explain how a ram pump works in the very beginning of the presentation (emphasize how the plate DOES NOT pump water, rather the pressure cycles)
- Explain set up more, and note the terms that you'll be using for the rest of the presentation (drive pipe, elevation head, influent, effluent)
- Efficiency:
-- Why does changing the slope of the ideal velocity graph in deceleration increase efficiency?
-- Explain air chamber more as part of experimental apparatus
-- Overall expand on what it means to "optimize efficiency"

Slide layouts and animations are AWESOME! Great job guys....I only have a lot of comments because I know ram pump the best out of my teams :)

**Comment by cheertsang** [comment]
**Final Presentation**
- [ ] Brief background @alyssaju 
- [x] Forces determined by pulley system @inigocabrera44 
- [ ] related to spring conversation - finding optimal spring constant @cheertsang 
- [x] Pressure sensor failures @ChingPangggg 
- [x] Re-designed ram pump with larger effluent diameter @ChingPangggg 
- [ ] Conclusions @alyssaju 
- [ ] Future work & summer plans @alyssaju
