### ISSUE TITLE
Things to Do

### ISSUE THREAD

**Issue by cheertsang** [AguaClara/ram_pump#65]
- [x] Verify terminal velocity by experimentation (terminal velocity found in Spring 2018 = .349 m/s)
- [x] Calculate theoretical water pumped
- [x] Fix code for experimental calculations
- [x] Calculations to find efficiency (actual/theoretical)

- [ ] Experiment with different parameters of experimentation (time of opening/closing valve)
- [x] Look at graphs at point where waste valve pressure goes above the air chamber pressure
- [x] Put pressure sensor closer to the effluent valve
- [ ] Account for air in tubing from air chamber

**Comment by cheertsang** [comment]
Height of drive pipe: 1.74 m
Height of drive pipe + water level in head tank: 2.06 m
diameter of drive pipe: 23.65 mm

**Comment by cheertsang** [comment]
- [x] adjust pressure sensor - move closer to effluent
- [x] re-run tests, measure height of water in air chamber - get a rough estimate of how much water is being pumped during each cycle

**Comment by cheertsang** [comment]
initial water level 6 cm from top of air chamber
initial pressure in air chamber: 698.97 cm
final water level 5 cm from top of air chamber

The volume of water pumped per 1 cycle is 0.5519 milliliter
The theoretical time period in which water is being pumped into the air chamber is 0.08193 second
The theoretical amount of water pumped is: 40.91 milliliter

similar to previous results
[Markdown file](https://github.com/AguaClara/ram_pump/blob/master/Spring%202019/4-16-2019_adjustedtubing.md)

**Comment by alyssaju** [comment]
**Preparations for EPA Conference (RamPump)**

- [ ] Make a poster to present
- [ ] Interactive activity showcasing rampump (check if station has electricity)

**Comment by cheertsang** [comment]
**Meeting with Monroe**
buy new pressure sensors, one that allows for higher pressures
redo pulley system tests to figure out what spring we need
- set the length of spring, solve for k
build new ram pump - effluent same size as waste check valve
- calculate headloss out of effluent in current setup?
- need to order brass nipple?
- something about the connection btwn the check valves

figure out setup for EPA

**Comment by alyssaju** [comment]
4/25 Meeting
- [ ] Write EPA grant!!!

**Comment by alyssaju** [comment]
### **Week of 6/3**
EPA Grant Proposal:
- [x] Send out emails for letters of support
- [ ] Finish Phase I of grant proposal
- [x] Brainstorm for Phase II of grant proposal (vc with team on Fri)
- [x] Complete and compile forms for grant proposal

Lab:
- [x] Cut tube for air tank and glue onto effluent pipe 
- [x] Test air chamber for water tightness

### **Week of 6/10**
EPA Grant Proposal:
- [ ] Begin writing Phase II and continue brainstorming project ideas for Phase II of grant proposal
- [x] Compile letters of support on Google Drive

EPA Conference:
- [ ] Work on poster (link on team Google Drive)
- [ ] Create checklist of what to bring to EPA Conference (e.g. parts of ram pump)

Lab:
- [ ] Install new pressure sensor (ProCoDA) 
- [ ] Run water through new ram pump; test to measure time that the valve is closed

### **Week of 6/17** _week of conference_
EPA Grant Proposal:
- [ ] Edit and finish up grant proposal

Lab:
- [ ] Trace complete pressure cycles of manually opening and closing of the ram pump
- [ ] Operate the pump for an extended period of time (maybe over a weekend?)

Other:
- [ ] Work on research report
