### ISSUE TITLE
EPA Conference Preparation

### ISSUE THREAD

**Issue by alyssaju** [AguaClara/ram_pump#68]
**To Do:**
- [ ] Make a poster to present
- [ ] Interactive activity showcasing ram pump (check if station has electricity)

**Comment by mailemccann** [comment]
I can start working on the poster this weekend?

**Comment by cheertsang** [comment]
**Priorities for Monday Meeting:**
- [ ] Start reorganizing research report to fit into Phase I section of EPA grant
- [ ] Organize sections we need for poster
- [ ] Organize parts we need to build new ram pump, see if we need to order more things

I was thinking we could have like 2 people working on these goals concurrently
