### ISSUE TITLE
Fabrication of new ram pump

### ISSUE THREAD

**Issue by ChingPangggg** [AguaClara/ram_pump#71]
@monroews We are not sure about what to buy for fabrication of a new ram pump.
1. First of all, for the rod that we needed to fabricate on our own, are we buying a fully threaded rod and then cut it down?
2. For the design that involve pipe union, should we get a threaded T-joint, and a brass or PVC pipe union ?

**Comment by ChingPangggg** [comment]
@monroews And is this what we should order? https://www.mcmaster.com/9162k476

**Comment by monroews** [comment]
COnsider meeting with Paul Charles to see if he would have a recommendation for an easier way to fabricate the rod.  We previously purchased a threaded rod and then cut it down.
The union looks good.
You can probably get a threaded Tee and short pipe nipples to connect between T and check valves.
You will also need nipples to connect union to check valves.

**Comment by ChingPangggg** [comment]
Also, since we now want the effluent to be 1" pipe size, we will need to fabricate a new air chamber, and then use an elbow to connect the air chamber with the check valve. Is this correct?

**Comment by monroews** [comment]
Draw a sketch and that will make it clear what pieces you need.

**Comment by ChingPangggg** [comment]
Tapping hole for pressure sensor on T-joint:
Drill bit: 7/16
Tap: 1/4in- 18 (or 16?)
