### ISSUE TITLE
Things to Do (Summer)

### ISSUE THREAD

**Issue by ChingPangggg** [AguaClara/ram_pump#77]
- [x]  Redo intrinsic spring value calculations
- [x]  Order springs that fit into the intrinsic k value graph
- [x]  Redo head loss calculations
- [x]  Trace complete pressure cycles of manually opening and closing of the ram pump
- [ ]  Operate the pump for an extended period of time (maybe over a weekend?)

**Comment by alyssaju** [comment]
Graphing one cycle of acceleration of driving head:

- [ ] Find flow rate when plate closes
- [ ] Calculate terminal velocity using Q = v*A
- [ ] Calculate time that the plate was closed (when P_wastevalve > P_airchamber)
- [ ] Find slope of deceleration after plate closes (a = v_terminal/t)
This is assuming that the velocity of water goes to 0 before the plate opens again.

- [ ] Modify acceleration input in the code by plugging in the correct v_terminal
- [ ] Graph and calculate the volume underneath the deceleration curve

**Comment by alyssaju** [comment]
Update schematic in summer 2019 report to account for new air chamber design

**Comment by alyssaju** [comment]
- [ ] Test with strong spring force
- [ ] Brainstorm better precision and measuring methods for finetuning the spring force with the lock nuts

**Comment by alyssaju** [comment]
Increase P + decrease I in PID to make it respond faster
