### ISSUE TITLE
Static Force of Water and Rod on Plate

### ISSUE THREAD

**Issue by alyssaju** [AguaClara/ram_pump#78]
The static force on the plate we calculated was **14.95N**. This was greater than our measured forces required to open (12.5N and 13.24N). Should we use this static force to find the optimal spring? 

**Code for calculating the static force on the plate**
d_plate = (1.125*u.inch).to(u.m) #diameter of check valve plate
L = 2.20*u.m #length of drive pipe
m = 0.1132*u.kg #mass of rod+plate+stopper
G = 9.807*u.m/u.s**2

_Calculating force of water on the plate:_

V = (np.pi * (d_plate/2)**2 * L).to(u.L)
F_water = (V * 1000*(u.kg/u.m**3) * G).to(u.N)

_Force from weight of rod:_

F_rod = (m * G).to(u.N)

_Total Static Force on Plate:_

F_plate = F_water + F_rod
print(F_plate)

**Comment by monroews** [comment]
The force you calculated and the forces you measured are reasonably consistent. So increase the force to be slightly greater than 15 N to ensure that valve opens when the water stops moving.
