### ISSUE TITLE
Running Pump Effluent with PID

### ISSUE THREAD

**Issue by ChingPangggg** [AguaClara/ram_pump#81]
hex nut located at 2.15 cm from union face when plate valve is opened and 3.35 cm from union face when plate valve is closed
Distance from spring side of plate to union face: 9.4 cm when plate is closed
Measured effluent flow using new design and spring K428:
913 mL /19.39 seconds = 47.0861269 mL/s = 0.0471 L/s

[First data collection](https://raw.githubusercontent.com/AguaClara/ram_pump/master/Summer%202019/Data%20Collection/New%20Air%20Chamber%20Design/7-25-2019_spring_K428_test1.xls): (no PID) 
start - end: 610 mL

[Second data collection](https://raw.githubusercontent.com/AguaClara/ram_pump/master/Summer%202019/Data%20Collection/New%20Air%20Chamber%20Design/7-25-2019_spring_K428_test2.xls): (no PID)
3 in pipe: 50.3 cm (start) (pass high pressure effluent) - 54.5 cm (end) (high pressure effluent valve closed)/15.98 s

[Third data collection](https://raw.githubusercontent.com/AguaClara/ram_pump/master/Summer%202019/Data%20Collection/New%20Air%20Chamber%20Design/7-25-2019_spring_K428_test3.xls): (with PID)
water level in air chamber started from 44 cm and then dropped to 43 and then ended at around 45 cm; distance of exposed rod from coupling nut = 101.16mm

Cycle period was not consistent (time period for every cycle)

**Comment by alyssaju** [comment]
**7-26-2019 spring K428**
The spring in all three trials had to be manually triggered several times before it pumped autonomously

[First data collection](https://raw.githubusercontent.com/AguaClara/ram_pump/master/Summer%202019/Data%20Collection/New%20Air%20Chamber%20Design/7-26-2019_spring_K428_test1.xls): 
- two pumps attached to air chamber
- distance of exposed rod from coupling nut = 99.94mm (1.22mm is about half a turn of coupling nut)

[Second data collection](https://raw.githubusercontent.com/AguaClara/ram_pump/master/Summer%202019/Data%20Collection/New%20Air%20Chamber%20Design/7-26-2019_spring_K428_test2.xls):
- distance of exposed rod from coupling nut = 98.55mm
![7-26-2019 K428 trial 2](https://user-images.githubusercontent.com/47133463/62065641-67edf100-b1fd-11e9-8c08-2f06457bcbdf.png)

[Third data collection](https://raw.githubusercontent.com/AguaClara/ram_pump/master/Summer%202019/Data%20Collection/New%20Air%20Chamber%20Design/7-26-2019_spring_K428_test3.xls):
- distance of exposed rod from coupling nut = 97.57mm
- slightly longer cycles
![7-26-2019 K428 trial 3](https://user-images.githubusercontent.com/47133463/62064979-0aa57000-b1fc-11e9-9ee2-585f9052aaf4.png)

Pressure spikes are very inconsistent and random.

**Comment by ChingPangggg** [comment]
**7-29-2019 spring K127**

First data collection:
- distance of exposed rod from coupling nut = 82.57mm
- started with empty air chamber

**Comment by ChingPangggg** [comment]
**7-31-2019 spring K127**

[Third data collection:](https://raw.githubusercontent.com/AguaClara/ram_pump/master/Summer%202019/Data%20Collection/New%20Air%20Chamber%20Design/7-31-2019_spring_K127_test3.xls)
- distance of exposed rod from end of rod to coupling nut = 100.12mm (too weak)
- 98.94mm (more consistent results)

**Comment by ChingPangggg** [comment]
**8-05-2019 spring K127**

trial 1:
- empty chamber
- not pressurized with peristaltic pump

trial 2: 
- pressurized with peristaltic pump when water level was in the middle of T-joint
- water poured into the bottom air chamber as PID control was on; inconsistent pump-cycles but water level was maintained steadily below the T-joint

trial 3: 
- pressurized with peristaltic pump when water level was above the T-joint
- PID control was not responding as fast as the pump (observe cyclic linear decrease and increase of air chamber pressure in graph)

trial 4: 
- changed the PID control: higher P (increases the responsiveness) and lower I (increases the importance of historical data which stabilizes our fluctuating data) --> P = 1.2; I = 100m
- pressurized with peristaltic pump when water level was above the T-joint

trial 5:
- same preset as trial 4 but with different PID settings (P = 1.5; I = 100m)

trial 6:
- rerun of trial 5
- cycle was pretty consistent, but it seemed inconsistent due to air bubbles that would form as air entered through the 1/4in check valve (test this hypothesis)
