### ISSUE TITLE
Inconsistent Pump Cycles - Spring K127

### ISSUE THREAD

**Issue by ChingPangggg** [AguaClara/ram_pump#83]
[7-31-19_spring_K127_trial 3](https://raw.githubusercontent.com/AguaClara/ram_pump/master/Summer%202019/Data%20Collection/New%20Air%20Chamber%20Design/7-31-2019_spring_K127_test3.xls)

Beginning when effluent valve was shut & air chamber was being pressurized w/ peristaltic pump:
![download (2)](https://user-images.githubusercontent.com/35943545/62240605-55aeb700-b3a5-11e9-98ec-a7a393767979.png)

After effluent valve was open & PID control was used to maintain pressure & air chamber was not being manually pressurized by pump:
(Zoom 1)
![download (1)](https://user-images.githubusercontent.com/35943545/62240385-de792300-b3a4-11e9-939b-78428f91dc00.png)

(Zoom 2)
![download](https://user-images.githubusercontent.com/35943545/62240284-a1149580-b3a4-11e9-9f33-31eae7682d33.png)

We noticed that there were some inconsistent cycles (as shown in zoom 1 & 2). Some of the pressure spikes were too close together. We can't get a sense of what might be causing these weird patterns such as the second cycle in the graph shown directly above. The adjustment of the spring length seems to be fine since the cycles were consistent in the beginning of this data collection when the effluent valve was closed. 

@monroews

**Comment by monroews** [comment]
Aren't these cycles much faster than optimal? Don't you want closer to a second for the cycle time?

**Comment by alyssaju** [comment]
Yes, we'll work on increasing the cycle times, but we wanted to primarily focus on keeping the cycles consistent. Wouldn't changing the cycle time not affect the inconsistent cycles? What would cause the inconsistent time cycles if we kept all the initial conditions the same?

**Comment by monroews** [comment]
Not sure, but I'd argue that there is no point in figuring this out UNLESS it is a problem when the cycle times are correct.
