### ISSUE TITLE
Air Chamber Design Dimensions - 8/2/19

### ISSUE THREAD

**Issue by ChingPangggg** [AguaClara/ram_pump#87]
**Offset T-joint design:**
- clear T-joint
- 7.5 cm of pipe attached below T-joint
- 75.0 cm of pipe attached above T-joint

**Comment by alyssaju** [comment]
**Initial elbow joint design:**
- ~123 cm or 4 ft
- barbed effluent valve at elbow joint

**Symmetric T-joint design:**
- 30 cm of 3in pipe above and below pipe
- T-joint itself was 13.6 cm long
