### ISSUE TITLE
Lab Bench set-up for Ram Pump

### ISSUE THREAD

**Issue by ChingPangggg** [AguaClara/ram_pump#91]
![image](https://user-images.githubusercontent.com/35943545/66601781-afd2b200-eb76-11e9-9f0c-777dd08e78a9.png)

We talked to Paul about fitting ram pump experimental setup into out lab bench, and Paul advise us to not drill holes on the bench, and instead take the table off or find a smaller top that would only occupy 1/2 of the current table space so we can put the ram pump set up in the other half. Do you have any suggestion about this?

@monroews

**Comment by monroews** [comment]
Why did he make this suggestion? Is it because drilling holes is hard or because he didn't want us to damage the lab benches?

Did he have any recommendations for an alternate top that we could drill holes through?

**Comment by ChingPangggg** [comment]
> Why did he make this suggestion? Is it because drilling holes is hard or because he didn't want us to damage the lab benches?
> 
> Did he have any recommendations for an alternate top that we could drill holes through?

He said it is very difficult to drill through the current lab benches and he also said that it would probably require a lot of effort and a special hole saw. He have not recommended another table top that we can drill through, but he said we could put a wooden top on the other half of the table just so we still have part of the lab bench to use, so I think it would also be possible to drill through the wooden top if we want to.
