### ISSUE TITLE
Calculating F_opened for new system

### ISSUE THREAD

**Issue by ChingPangggg** [AguaClara/ram_pump#94]
@monroews 
We are having trouble finding the the new F_{opened} for the new system.
Since we changed the height of the water running through the ram pump, which means the the velocity is different right now. For F_{closed}, we can find it using the hydrostatic equation.
However, for F_{opened}, if we don't want to install the pulley system again, is there a way to find it analytically?
We weren't sure of this thought process is valid so we were wondering if it is somewhat reasonable to say that (ignoring head losses from friction since it is much smaller than the head loss through the ram pump), if you subtract the head loss from due to the ram pump from the potential energy of our system, you get a potential energy with an adjusted height that would give the same velocity at the bottom of the drive pipe as our current system, but in this new system we don't have head loss and can now use Bernoulli eq. to find the pressure at the bottom of the drive pipe and ultimately find the force on the plate using this pressure? These are clearly big assumptions and jumps to make so we were skeptical of its validity.

**Comment by monroews** [comment]
We'd expect the force to be proportional to the velocity squared. And we'd expect velocity squared to scale with the available head. (hL = K * V*2/(2g) where hL is the Potential energy)
So I think that means that the force simply scales linearly with height. Check my reasoning.

Can you design a force system that allows you to independently adjust the two forces? It would make tuning be intuitive and fun.
